const CONFIG = {
    chuRe: "Chú rể",
    coDau: "Cô dâu",
    chuReFull: "Họ và tên chú rể",
    coDauFull: "Họ và tên cô dâu",
    danhXungChuRe: "TRƯỞNG NAM",
    danhXungCoDau: "TRƯỞNG NỮ",
    baChuRe: "Ba chú rể",
    meChuRe: "Mẹ chú rể",
    baCoDau: "Ba cô dâu",
    meCodau: "Mẹ cô dâu",
    ngayCuoi: "20 . 10 . 2027",
    diaChiPhuongChuRe: "720 Điện Biên Phủ",
    // diaChiTPChuRe: "Thạnh Mỹ Tây TP. Hồ Chí Minh",
    diaChiPhuongCoDau: "192 Nguyễn văn Hưởng",
    // diaChiTPCoDau: "An Khánh, Hồ Chí Minh",
    // thanhDuongGiaoXu: "THÁNH ĐƯỜNG GIÁO XỨ...",
    // gioLeNhaTho: "VÀO LÚC 04:30 THỨ BẢY",
    // thuLamLe: "THỨ BẢY",
    // ngayLamLe: "19.09.2028",
    // nhamNgay: "(Nhằm ngày 09 tháng 08 năm ...)",
    // tiecCuoiTai: "NHÀ HÀNG",
    tenNhaHang: "Trung tâm hội nghị tiệc cưới Royal Center",
    diaChiPhuongTiecCuoi: "180/4 Song Hành, Ấp 61",
    diaChiTpTiecCuoi: "X. Bà Điểm, TP. HCM",
    gioTiecCuoiDienRa: "11:00",
    thuTiecCuoiDienRa: "CHỦ NHẬT",
    ngayTiecCuoiDienRa: "20",
    thangTiecCuoiDienRa: "THÁNG 09",
    namTiecCuoiDienRa: "2030",
    nhamNgayTiecCuoiDienRa: "(NHẰM NGÀY 10 THÁNG 12 NĂM ....)",
    // ngayThangNamDienRaTiecCuoi:"2026-12-25T05:00:00Z",
    ngayThangNamDienRaTiecCuoi: new Date(Date.now() + 24 * 60 * 60 * 1000),
    totalNumberImage : 8,
    limit_loiChuc: 7000,
    limit_NickName: 3000,
  
    // diaChi: "TP. Hồ Chí Minh",
  };
  